spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/ec_order"
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    schemas: public
  application:
    name: order-service
  rabbitmq:
    transaction-queue-name: TRANSACTION_QUEUE
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      retry:
        enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 10001
